
/*
 *	This file was automatically generated by dbusxx-xml2cpp; DO NOT EDIT!
 */

#ifndef __dbusxx__fapolicyd_analyzer_client_proxy_hpp__PROXY_MARSHAL_H
#define __dbusxx__fapolicyd_analyzer_client_proxy_hpp__PROXY_MARSHAL_H

#include <dbus-c++/dbus.h>
#include <cassert>

namespace org {
namespace freedesktop {
namespace DBus {
namespace fapolicyd {

class analyzer_proxy
: public ::DBus::InterfaceProxy
{
public:

    analyzer_proxy()
    : ::DBus::InterfaceProxy("org.freedesktop.DBus.fapolicyd.analyzer")
    {
    }

public:

    /* properties exported by this interface */
public:

    /* methods exported by this interface,
     * this functions will invoke the corresponding methods on the remote objects
     */
    std::vector< ::DBus::Struct< std::string, std::vector< std::string > > > RpmDbAsTable()
    {
        ::DBus::CallMessage call;
        call.member("RpmDbAsTable");
        ::DBus::Message ret = invoke_method (call);
        ::DBus::MessageIter ri = ret.reader();

        std::vector< ::DBus::Struct< std::string, std::vector< std::string > > > argout;
        ri >> argout;
        return argout;
    }


public:

    /* signal handlers for this interface
     */

private:

    /* unmarshalers (to unpack the DBus message before calling the actual signal handler)
     */
};

} } } } 
#endif //__dbusxx__fapolicyd_analyzer_client_proxy_hpp__PROXY_MARSHAL_H
